spring:
  datasource:
    username: root
    password: faf59oh8
    url: jdbc:mysql://47.74.89.29:3306/osystem_admin_sms
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  config-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000